### ISSUE TITLE
Routes does not work when running under windows

### ISSUE THREAD

**Issue by p4fg** [tarruda/node-flask-router#1]
Routing using node-flask-router does not work when running on windows.
The problem seems to be the following statement:

p = path.normalize(urlObj.pathname)

Which, on windows, will replace all slashes with backslashes, so /test becomes \test.

**Comment by tarruda** [comment]
I'm pretty busy to fix this right now, perhaps you want to send a pull request?

**Comment by tarruda** [comment]
Please confirm this is was fixed by last [merge](https://github.com/tarruda/node-flask-router/pull/2). If so feel free to close the issue :)

**Comment by p4fg** [comment]
Problem solved! Thx!
